Ruby ART19 Onboarding exercise
mghorb/ruby-blog pull request #1
Opened 2021-12-09 16:40 UTC by mghorb

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +    render json: @tags, status: 200
This index endpoint shouldn't care about the article id.  Just return all the tags.
- [ ] GET /tags?q=
  - the `q`  param should be used to do a partial (ILIKE) text match on the tag name

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +  def new
This action isn't needed for a json api.  The client application should construct the new tag and save it via `POST /tags`

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +    @tags = Tag.all
Show actions should return only a single resource.

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +      render json: {error: "Tag not created."}
In this case we'll return the validation errors in the resopnse. As well as a 422 status code.

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +      render json: {error: "Tag cannot be updated."}
Same here.  For a proper json api you'll need to return a 422 status code and validation error messages.

2021-12-09 18:36 UTC, demersus commented on app/controllers/api/v1/tags_controller.rb
> +    render json: "Tag deleted."
Our typical pattern here would be to return an empty body with a 204 status code.

2021-12-09 18:36 UTC, demersus commented on app/controllers/comments_controller.rb
> +    VerifyComment.perform_later(@comment)
Please trigger the verification worker from an active record callback in the model.  If a comment would be created through another entry-point, we'd want the same verification process to happen.

2021-12-09 18:36 UTC, demersus commented on app/controllers/comments_controller.rb
> +      VerifyComment.perform_later(@comment)
Same here with an ActiveRecord callback. 
Also, the comment needs to be changed to the 'submitted' state on every update.  So you could trigger the VerifyComment worker after save, only when in the 'submitted' state.

2021-12-09 18:36 UTC, demersus commented on app/controllers/verify_comment.rb
> +  TRIGGER_WORDS = ['hate','bad','boo', ':(']
We'll freeze constants.
```suggestion
  TRIGGER_WORDS = ['hate','bad','boo', ':('].freeze
```

Another thing you'll notice is that we will put the [magic comment](https://www.mikeperham.com/2018/02/28/ruby-optimization-with-one-magic-comment/) at the top of every ruby file to freeze string literals:
```
# frozen_string_literal: true

class ...
```

2021-12-09 18:36 UTC, demersus commented on app/models/concerns/approval.rb
> +  APPROVAL_STATUSES = ['submitted', 'approved', 'flagged']
```suggestion
  APPROVAL_STATUSES = ['submitted', 'approved', 'flagged'].freeze
```

2021-12-09 18:36 UTC, demersus commented on db/schema.rb
> +    t.string "status"
default status should be 'submitted'

2021-12-29 19:44 UTC, mghorb commented on spec/controllers/articles_controller_spec.rb
> +    # Was having trouble with this one - I tried (with 'shoulda-matchers' lib)
describe '#verify_comment' do

2021-12-29 19:45 UTC, mghorb commented on spec/controllers/articles_controller_spec.rb
> +    # Was having trouble with this one - I tried (with 'shoulda-matchers' lib)
@demersus Tried to explain what I was having trouble here with, feel free to PM me

2022-01-04 21:52 UTC, demersus requested changes
Looks like you're making good progress here.

I'd like to see you continue to improve this with request specs, and specs around the comment model's statuses and changing body.  All resources will need to respond to JSON format also.

2022-01-04 21:52 UTC, demersus commented on spec/controllers/articles_controller_spec.rb
> +    # it 'checks uniqueness of title' do
You can use the block form with `except`:
```ruby
let(:article) { FactoryBot.create(:article) }

it 'validates the uniqueness of title' do
  expect { FactoryBot.create(:article, title: article.title) }.to raise_error 'Validation failed: Title has already been taken'
end
```

This allows RSpec to defer execution until you chain the assertion from it.

2022-01-04 21:52 UTC, demersus commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
This assertion should be in the spec for VerifyComment. 

Here, I would use rspec mocks to check if the article is queued for verification:

```ruby
before { allow(VerifyComment).to receive(:perform_async) }

it 'will queue a VerifyComment worker when created' do
  article = FactoryBot.create(:article)
  expect(VerifyComment).to have_received(:perform_async).with(article.id)
end
```

2022-01-04 21:52 UTC, demersus commented on spec/factories.rb
> +    title { 'Article x' }
In your block here, you can get an argument for a counter.  Then you can add that to your title to ensure multiple created have unique titles.

`title { |i| "Aricle #{i}" }`

2022-01-04 21:52 UTC, demersus commented on spec/controllers/comments_controller_spec.rb
> +require 'rails_helper'
These appear to be model specs.  I'd put this in spec/models/comment_spec.rb 
Similarly with the articles_controller_spec.  You are testing the model.  Those assertions belong in a model spec.

You'll need to add request specs to cover the request over http through the response.   Controller specs are then only used if there's unit-level complexity to test.   Otherwise, request specs are generally enough for standard API controllers.

2022-01-04 21:52 UTC, demersus commented on db/migrate/20211207202435_create_join_table_articles_tags.rb
> +    create_join_table :articles, :tags do |t|
Let me give you a hint here.  If you turn this into an actual model, you can get a counter cache macro to cover the tag counter acceptance criteria.

https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache

2022-01-11 17:46 UTC, mghorb commented on app/workers/verify_comment.rb
> +      comment.update_column(:status, 'flagged')
Oh yeah so I had some trouble with this which is why I used `update_column`, basically like a stack overflow. `after_save` will trigger after update and will trigger this function, which will trigger the `comment.update`  which will trigger `after_save`..... 

If you have another solution to avoid this infinite loop please lmk, I spent a while trying to do this so I found `update_column` what worked for me

2022-01-12 00:09 UTC, mghorb commented on spec/controllers/articles_controller_spec.rb
> +      @article = FactoryBot.create(:article)
Sorry just need a little more context on where specifically this would go? because otherwise wouldnt @article in the instances be null?

2022-01-12 20:41 UTC, mghorb commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
Ok so i've tried `.to receive(:perform_async)`, which gives me: 
```
 Failure/Error: before { allow(VerifyComment).to receive(:perform_async) }
       VerifyComment does not implement: perform_async
     # ./spec/workers/verify_comment_spec.rb:10:in `block (3 levels) in <main>'
```

and also tried `.to receive(:perform_async)`:
```
(VerifyComment (class)).perform_later(50)
           expected: 1 time with arguments: (50)
           received: 0 times
```
any thoughts?

2022-01-12 21:54 UTC, demersus commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
I see now that you are inheriting from ActiveJob instead of Sidekiq::Worker.  In this case, the method would be: #perform_later.  Instead of #perform_async

2022-01-12 21:56 UTC, demersus commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
We recommend sidekiq directly in our systems:  https://andycroll.com/ruby/use-sidekiq-directly-not-through-active-job/

This is fine though for this application.  The general concepts are the same.

2022-01-13 16:49 UTC, mghorb commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
OK thanks! let me try again

2022-01-13 18:39 UTC, mghorb commented on spec/controllers/comments_controller_spec.rb
> +      VerifyComment.new.perform(@comment)
Oh yeah I did try :perform_later, gave me the this exception: 
```
(VerifyComment (class)).perform_later(50)
           expected: 1 time with arguments: (50)
           received: 0 times
```

Let me try to investigate why ..

2022-04-19 04:39 UTC, closed without merging